import Head from "next/head";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import Home from "@/components/Home";
import About from "@/components/About";
import Portfolio from "@/components/Portfolio";
import Contact from "@/components/Contact";
import clsx from "clsx";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function MyHome() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(inter.className, "text-accent-200")}>
        <Nav />
        <Home />
        <About />
        <Portfolio />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
